### ISSUE TITLE
Push not working on public repository

### ISSUE THREAD

**Issue by sdruskat** [adr/adr-manager#149]
Thanks for creating this tool!

I have started using ADR Manager on a new empty repo in one of my orgs. While editing works fine, commit and push does nothing.

Initially, newly created ADRs were only shown as empty checkboxes in the commit & push dialog, the respective ADRs were still marked with an asterisk in the list of ADRs for the repository.

After adding some ADRs (MADR files) manually to `repo/docs/adr/`, the file names show up in commit & push, but push again, doesn't work. Happy to supply more info if needed and contribute to a resolution.

**Comment by koppor** [comment]
I experienced the same, but had no time to dive into the issue.

Maybe you can add some cypress test to https://github.com/adr/adr-manager/blob/main/cypress/integration/adrManagerTest/AddNewAdr.js so that we can track down the issue further?

**Comment by sdruskat** [comment]
Thanks, will do but will take a while as I'm currently swamped.
