### ISSUE TITLE
Heroku HTTPS is not using valid SSL

### ISSUE THREAD

**Issue by bdwellons** [adr/adr-manager#152]
I'm blocked from adding Github repos to ADR-Manager:

adr-manager-auth.herokuapp.com normally uses encryption to protect your information. When Chrome tried to connect to adr-manager-auth.herokuapp.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be adr-manager-auth.herokuapp.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit adr-manager-auth.herokuapp.com right now because the website sent scrambled credentials that Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by xJREB** [comment]
Is this still an issue? I can't seem to reproduce this, neither in Chrome nor in Firefox (both on Windows 10).
